services:
  - type: web
    name: sticonf
    env: python
    pythonVersion: 3.11.4
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn sticonf.wsgi:application --worker-tmp-dir /dev/shm --timeout 120"
    envVars:
      - key: DEBUG
        value: "False"
