# Generated by Django 5.2.6 on 2026-04-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('sponsorship', 'Sponsorship'), ('speaking', 'Speaking Opportunity'), ('partnership', 'Partnership'), ('media', 'Media/Press'), ('other', 'Other')], default='general', max_length=50)),
                ('interest', models.TextField(help_text='Message/Inquiry details')),
                ('read', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True, help_text='Internal notes on response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('student', 'Student'), ('academic', 'Academic/Researcher'), ('industry', 'Industry Professional'), ('government', 'Government'), ('investor', 'Investor'), ('startup', 'Startup Founder'), ('other', 'Other')], default='other', max_length=50)),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=100)),
                ('interest', models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('iot', 'IoT & Connected Devices'), ('blockchain', 'Blockchain & Web3'), ('biotech', 'Biotechnology'), ('cleantech', 'Clean Technology'), ('agritech', 'AgriTech'), ('fintech', 'FinTech'), ('other', 'Other')], default='other', max_length=200)),
                ('brevo_synced', models.BooleanField(default=False, help_text='Whether synced to Brevo mailing list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN', max_digits=12)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(help_text='Flutterwave transaction reference', max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sponsorshiptier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
